name: Replicate dbt Cloud Jobs from YAML
run-name: Running dbt-jobs-as-code to replicate dbt Cloud jobs from YAML
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  run-python-script:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.x"

      - name: Install dbt-jobs-as-code
        run: pip install git+https://github.com/dbt-labs/dbt-jobs-as-code.git@v0.4.0

      - name: Run dbt-jobs-as-code
        run: dbt-jobs-as-code sync jobs/jobs.yml
        env: 
          DBT_API_KEY: "${{secrets.DBT_API_KEY}}"
          # DBT_BASE_URL is optional
          # DBT_BASE_URL: "${{secrets.DBT_BASE_URL}}"
